config = {
    "debate_topic": "",
    "base_answer": "",
    "debate_answer": "",
    "player_meta_prompt": "You are a debater. Hello and welcome to the debate. It's not necessary to fully agree with each other's perspectives, as our objective is to find the correct answer.\nThe debate topic is stated as follows:\n##debate_topic##.\n Debate in in free text format",
    "moderator_meta_prompt": "You are a moderator. There will be three debaters involved in a debate. They will present their answers and discuss their perspectives on the following topic: \"##debate_topic##\"\nAt the end of each round, you will evaluate answers and decide which is correct. Please output your answer strictly in JSON format without any code block markers or additional text. Do not include '```json' or '```' in your response. with the format as follows: {\"Whether there is a preference\": \"Yes or No\", \"Supported Side\": \"Affirmative or Negative\", \"Reason\": \"\", \"debate_answer\": \"\"}. Please strictly output in JSON format, do not output irrelevant content.",
    "affirmative_prompt": "##debate_topic##",
    "negative_prompt": "##aff_ans##\n\nYou disagree with my answer. Provide your answer and reasons.",
    "third_part_prompt": "Present a third argument that either directly challenges or introduces a new perspective distinct from the first two:\n\nAffirmative side: ##aff_ans##\nNegative side: ##neg_ans##\n\n . Avoid simply agreeing or finding a middle ground—focus on adding depth or tension to the discussion by identifying flaws, assumptions, or alternative viewpoints not yet addressed.",
    "moderator_prompt": "Now the ##round## round of debate for both sides has ended.\n\nAffirmative side arguing:\n##aff_ans##\n\nNegative side arguing: ##neg_ans##\n\n \n\nThird part side arguing:\n##third_ans##\n\n You, as the moderator, will evaluate all sides' answers and determine if there is a clear preference for an answer candidate or if they are agreeing with each other. If so, please summarize your reasons for supporting affirmative/negative/third side and give the final answer that you think is correct, and the debate will conclude. If not, the debate will continue to the next round. ",
    "judge_prompt_last1": "Affirmative side arguing: ##aff_ans##\n\nNegative side arguing: ##neg_ans##\n\n \n\nThird part side arguing:\n##third_ans##\n\n Now, what answer candidates do we have? Present them without reasons.",
    "judge_prompt_last2": "Therefore, ##debate_topic##\nPlease summarize your reasons and give the final answer that you think is correct. Now please output your answer in json format, with the format as follows: {\"Reason\": \"\", \"debate_answer\": \"\"}. Please strictly output in JSON format, do not output irrelevant content.",
    "debate_prompt": "##oppo_ans##\n\n ##oppo_ans2##\n\n  Do you agree with one of this perspectives about your original answer ##Your_answer##\n\n? Please provide your reasons and answer.Additionally, you have access to the full debate history for extra context.Do not use JSON or structured formats in your response."
}